// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBSN(arg1:boolean):Promise<string>;

export function IsValidBSN(arg1:string):Promise<boolean>;
